//go:build !linux

// This file exists ONLY to satisfy editor tooling (gopls) and `go build` on
// non-Linux hosts (macOS/Windows). The real definitions of these symbols are
// generated by `go generate` (bpf2go) into guard_bpfel.go / guard_bpfeb.go,
// which carry a `linux` build tag and are produced inside the container at
// image-build time. On a dev host those generated files are absent, so
// without these stubs the editor reports `undefined: loadGuard`,
// `undefined: guardObjects`, `undefined: guardAddressKey` throughout main.go.
//
// The `!linux` constraint guarantees this file NEVER participates in the real
// build: on Linux the generated files provide these symbols instead, so the
// two never collide.
package main

import "github.com/cilium/ebpf"

type guardAddressKey struct {
	Address uint32
	Port    uint16
}

type guardObjects struct {
	Guard       *ebpf.Program
	BlockEvents *ebpf.Map
	Blocklist   *ebpf.Map
	PktStats    *ebpf.Map
	Target      *ebpf.Map
}

func (o *guardObjects) Close() error { return nil }

func loadGuard() (*ebpf.CollectionSpec, error) { return nil, nil }
